# Generated by Django 5.1.3 on 2025-07-08 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('countries', models.CharField(max_length=255)),
                ('flag', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.faqcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('from_currency', models.CharField(choices=[('USD', 'USD (Dollar américain)'), ('XAF', 'XAF (Franc CFA BEAC)'), ('GNF', 'GNF (Franc guinéen)'), ('CAD', 'CAD (Dollar canadien)'), ('XOF', 'XOF (Franc CFA BCEAO)'), ('EUR', 'EUR (Euro)'), ('MAD', 'MAD (Dirham marocain)'), ('TND', 'TND (Dinar tunisien)'), ('EUR', 'EUR (Euro)'), ('CNY', 'CNY (Yuan chinois)'), ('JPY', 'JPY (Yen japonais)'), ('RUB', 'RUB (Rouble russe)')], default='USD', max_length=20)),
                ('to_currency', models.CharField(choices=[('USD', 'USD (Dollar américain)'), ('XAF', 'XAF (Franc CFA BEAC)'), ('GNF', 'GNF (Franc guinéen)'), ('CAD', 'CAD (Dollar canadien)'), ('XOF', 'XOF (Franc CFA BCEAO)'), ('EUR', 'EUR (Euro)'), ('MAD', 'MAD (Dirham marocain)'), ('TND', 'TND (Dinar tunisien)'), ('EUR', 'EUR (Euro)'), ('CNY', 'CNY (Yuan chinois)'), ('JPY', 'JPY (Yen japonais)'), ('RUB', 'RUB (Rouble russe)')], default='XAF', max_length=20)),
                ('from_country', models.CharField(choices=[('', 'Sélectionnez un pays'), ('US', 'États-Unis'), ('GA', 'Gabon'), ('GN', 'Guinée'), ('CA', 'Canada'), ('BF', 'Burkina Faso'), ('MA', 'Maroc'), ('TN', 'Tunisie'), ('ES', 'Espagne'), ('CN', 'Chine'), ('JP', 'Japon'), ('RU', 'Russie'), ('ML', 'Mali'), ('FR', 'France'), ('NI', 'Niger')], default='', max_length=15)),
                ('to_country', models.CharField(choices=[('', 'Sélectionnez un pays'), ('US', 'États-Unis'), ('GA', 'Gabon'), ('GN', 'Guinée'), ('CA', 'Canada'), ('BF', 'Burkina Faso'), ('MA', 'Maroc'), ('TN', 'Tunisie'), ('ES', 'Espagne'), ('CN', 'Chine'), ('JP', 'Japon'), ('RU', 'Russie'), ('ML', 'Mali'), ('FR', 'France'), ('NI', 'Niger')], default='', max_length=15)),
                ('payment_method', models.CharField(choices=[('', 'Sélectionnez une méthode'), ('card', 'Carte de crédit/débit'), ('bank', 'Compte bancaire'), ('cash', 'Espèces')], default='', max_length=50)),
                ('fees', models.DecimalField(decimal_places=15, max_digits=20)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=20)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
